# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-toml
    -   id: check-xml
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: detect-aws-credentials
        args: [--allow-missing-credentials]
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
        args: ["--remove"]
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
        args: ["--fix=lf"]
    -   id: name-tests-test
        args: [--django]  # to match `test*.py`.
    -   id: no-commit-to-branch
        args: [--branch, staging, --branch, master, --branch, main]
    -   id: pretty-format-json
        args: [--autofix]
    -   id: requirements-txt-fixer
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        # max-line-length setting is the same as black
        # commit cannot be done when cyclomatic complexity is more than 11.
        args: [--max-line-length, "88", --ignore=E402, --max-complexity, "11", --max-expression-complexity=7, --max-cognitive-complexity=11]
        additional_dependencies: [flake8-bugbear, flake8-builtins, flake8-eradicate, pep8-naming, flake8-expression-complexity, flake8-cognitive-complexity]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.800
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [tokenize-rt==3.2.0]
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        args: [--skip-string-normalization]
        language_version: python3
-   repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]
    # for docstrings in python codes
-   repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
    -   id: docformatter
        args: [--in-place]
    # for markdown
-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4
    hooks:
      - id: markdownlint
        args: ["-r", "~MD002,~MD013,~MD024,~MD029,~MD033,~MD034,~MD036"]
